import useState from 'react'
import Head from 'next/head'
import Image from 'next/image'
import headerLady from '../public/images/girlheader.jpg'
import glasses from '../public/images/glasses.jpg'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {BsArrowRightShort} from 'react-icons/bs'
import {AiFillStar,AiOutlineSearch,AiOutlineShoppingCart,AiOutlineUser} from 'react-icons/ai'
import {TbWorld} from 'react-icons/tb'
import {MdOutlineLocalShipping} from 'react-icons/md'
import {BiLockAlt} from 'react-icons/bi'



const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  let clickVal;
  return (
    <>
      <Head>
        <title>Shopi | Online Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col lg:max-h-screen lg:scrollbar lg:scrollbar-thumb-shopiBlack lg:scrollbar-track-gray-100">
        <div className="top relative lg:flex lg:min-h-screen lg:flex-col ">
          <nav className='p-4 flex w-full justify-between items-center lg:p-14'>
            <div className="logo w-5 h-5 bg-black rounded-full">
              
            </div>
            <div className="links hidden lg:block">
              <ul className='flex gap-10 font-bold text-shopiBlack/80 text-xl'>
                <li><button className='group relative py-2'><div className="transition origin-left under absolute w-full h-[3px] bg-shopiBlack/70 bottom-0 scale-x-0 group-hover:scale-x-100"></div>Home</button></li>
                <li><button className='group relative py-2'><div className="transition origin-left under absolute w-full h-[3px] bg-shopiBlack/70 bottom-0 scale-x-0 group-hover:scale-x-100"></div>Collections</button></li>
                <li><button className='group relative py-2'><div className="transition origin-left under absolute w-full h-[3px] bg-shopiBlack/70 bottom-0 scale-x-0 group-hover:scale-x-100"></div>Brands</button></li>
                <li><button className='group relative py-2'><div className="transition origin-left under absolute w-full h-[3px] bg-shopiBlack/70 bottom-0 scale-x-0 group-hover:scale-x-100"></div>New</button></li>
                <li><button className='group relative py-2'><div className="transition origin-left under absolute w-full h-[3px] bg-shopiBlack/70 bottom-0 scale-x-0 group-hover:scale-x-100"></div>Sales</button></li>
              </ul>
            </div>
            <div className="sidenav text-3xl hidden lg:flex gap-5 ">
              <AiOutlineSearch/>
              <AiOutlineShoppingCart/>
              <AiOutlineUser/>
            </div>
            <div className="hamburger flex flex-col gap-[.2rem] items-end lg:hidden">
              <div className="line w-[.75rem] h-[.3rem] bg-black"></div>
              <div className="line w-[1.5rem] h-[.3rem] bg-black"></div>
              <div className="line w-[1.5rem] h-[.3rem] bg-black"></div>
            </div>
          </nav>
          <header className='relative m-4 border-l-[3px] border-shopiBlack p-4 lg:p-14 lg:m-14 lg:flex lg:flex-col lg:gap-0 lg:grow lg:mb-0'>
            <h1 className=' font-semibold text-2xl lg:text-7xl'>
            Different style and fashion <br /> for everyone
            </h1>
            <p className='hidden lg:block lg:text-xl lg:font-semibold text-shopiBlack/70 lg:mt-10'>Create your own personal and special style among the <br /> new summer collection and be different from others.</p>
            <button className='bg-shopiBlack text-white py-3 px-5 text-lg mt-8 mb-20 flex items-center gap-2 self-start z-10'>Shop Collection <BsArrowRightShort className='text-3xl'/></button>
            <Image src={headerLady} className=" md:absolute md:right-0 md:top-0 md:w-1/2 md:h-screen hidden md:mt-10 lg:block lg:object-cover lg:-z-10 lg:object-top lg:-translate-y-20 lg:translate-x-14 lg:w-[50vw]" alt=""/>

          </header>
          <div className="floatyStuff lg:absolute lg:bottom-10 lg:w-full lg:overflow-hidden">
            <section className='m-4 ml-5 -mt-20 h-[35vmax] relative lg:m-0 lg:left-1/3 lg:max-w-fill'>
              <Image src={headerLady} className="ml-auto w-1/2 h-full object-cover lg:hidden" alt=""/>
              <div className="flex gap-3 w-fit card absolute bottom-5  p-3 bg-white translate-x-8 shadow-xl lg:translate-x-24 lg:text-xl lg:pr-10">
                <Image className='w-[4rem] aspect-square object-cover lg:w-[8rem]' src={glasses} alt=''/>
                <div className="text flex flex-col justify-between lg:justify-center lg:gap-3">
                  <h1 className=' font-semibold lg:font-bold lg:text-shopiBlack/70 '>Sudown Sunglasses</h1>
                  <p className='text-sm lg:text-base lg:-mt-3 lg:font-bold lg:text-shopiBlack/70'>$ 24.80</p>
                  <div className="stars flex lg:text-base">
                    <AiFillStar />
                    <AiFillStar />
                    <AiFillStar />
                    <AiFillStar />
                    <AiFillStar />
                  </div>
                </div>
              </div>
              <div className="flex gap-3 w-fit card absolute bottom-5 -translate-y-[125%] p-3 bg-white shadow-xl lg:text-xl lg:pr-10">
                <Image className='w-[4rem] aspect-square object-cover lg:w-[8rem]' src={glasses} alt=''/>
                <div className="text flex flex-col justify-between lg:justify-center lg:gap-3">
                  <h1 className=' font-semibold lg:font-bold lg:text-shopiBlack/70 '>Sudown Sunglasses</h1>
                  <p className='text-sm lg:text-base lg:-mt-3 lg:font-bold lg:text-shopiBlack/70'>$ 24.80</p>
                  <div className="stars flex lg:text-base">
                    <AiFillStar />
                    <AiFillStar />
                    <AiFillStar />
                    <AiFillStar />
                    <AiFillStar />
                  </div>
                </div>
              </div>
            </section>
            <section className='p-4 mb-4 flex social-proof lg:absolute lg:bottom-10 lg:left-24 lg:w-auto lg:gap-10'>
              <div className="hc w-1/2 lg:w-auto">
                <h1 className=' font-bold text-xl lg:text-2xl'>2K+</h1>
                <p className='font-semibold lg:text-lg'>Happy Customers</p>
              </div>
              <div className="ib w-1/2 lg:w-auto">
                <h1 className=' font-bold text-xl lg:text-2xl'>30+</h1>
                <p className='font-semibold lg:text-lg'>International Brands</p>
              </div>
            </section>
          </div>
        </div>
        <section className=' bg-shopiBlack px-10 py-5 text-white flex flex-col lg:flex-row lg:justify-around lg:py-20'>
          <div className="desc text-center flex flex-col items-center my-4 lg:flex-row lg:items-start lg:text-left lg:gap-5">
            <div className="logo text-4xl w-fit"><TbWorld/></div>
            <div className="text w-[10rem]">
              <h1 className="font-bold my-2">Worldwide Shop</h1>
              <p className=' text-[.8rem] text-white/70'>We dont limit our store buy from wherever you are.</p>
            </div>
          </div>
          <div className="desc text-center flex flex-col items-center my-4 lg:flex-row lg:items-start lg:text-left lg:gap-5">
            <div className="logo text-4xl w-fit"><MdOutlineLocalShipping/></div>
            <div className="text w-[10rem]">
              <h1 className="font-bold my-2">Free Shipping</h1>
              <p className=' text-[.8rem] text-white/70'>In all your purchases over $200 UDS.</p>
            </div>
          </div>
          <div className="desc text-center flex flex-col items-center my-4 lg:flex-row lg:items-start lg:text-left lg:gap-5">
            <div className="logo text-4xl w-fit"><BiLockAlt/></div>
            <div className="text w-[10rem]">
              <h1 className="font-bold my-2">Secure Payment</h1>
              <p className=' text-[.8rem] text-white/70'>Your data is protected and your Payments too.</p>
            </div>
          </div>
        </section>
        <section className="SC bg-white mb-5">
          <header className='p-5 pb-0 flex justify-between my-5'>
            <h1 className='font-bold'>The Summer Collection</h1>
            <div className="collectionPicker flex gap-2 text-black/50 font-bold">
              <div onClick={(e)=>{clickVal = 1; console.log(e.target)}} className={`01 cursor-pointer ${clickVal===1?"font-bold text-lg text-black":""} `}>01</div>
              <div onClick={(e)=>{clickVal = 2; console.log(e.target)}} className={`02 cursor-pointer ${clickVal===2?"font-bold text-lg text-black":""} `}>02</div>
              <div onClick={(e)=>{clickVal = 3; console.log(e.target)}} className={`03 cursor-pointer ${clickVal===3?"font-bold text-lg text-black":""} `}>03</div>
              <div onClick={(e)=>{clickVal = 4; console.log(e.target)}} className={`04 cursor-pointer ${clickVal===4?"font-bold text-lg text-black":""} `}>04</div>
            </div>
          </header>
          <div className="slider my-10 flex  overflow-x-scroll">
            <div className="scCard px-2 w-fit">
              <div className="image bg-shopiBlack/10 w-60 h-60 grid place-content-center">
                <button className='text-white bg-shopiBlack p-4 flex items-center'>Quick View <BsArrowRightShort className='text-xl'/></button>
              </div>
              <div className="text py-3">
                <p className='font-bold'>Teffta Blouse</p> 
                <p>$80.00</p>
              </div>
            </div>
            <div className="scCard px-2 w-fit">
              <div className="image bg-shopiBlack/10 w-60 h-60 grid place-content-center">
                <button className='text-white bg-shopiBlack p-4 flex items-center'>Quick View <BsArrowRightShort className='text-xl'/></button>
              </div>
              <div className="text py-3">
                <p className='font-bold'>Teffta Blouse</p> 
                <p>$80.00</p>
              </div>
            </div>
          </div>
        </section>
        <section className="DM px-4 py-7 bg-shopiBlack text-white lg:flex lg:justify-between lg:px-10 lg:py-20">
          <div className="text relative pl-5 flex flex-col items-start gap-5 lg:px-10 lg:gap-10">
            <div className="borderSide80 h-4/5 w-[2px] bg-white absolute left-0 bottom-0"></div>
            <h1 className=' font-semibold text-lg lg:text-2xl'>Do Not Miss The Clothes In <br /> Different Styles</h1>
            <p className=' capitalize lg:max-w-lg'>See Attractive Men{"'"}<span className=' lowercase'>s</span> And Women{"'"}<span className=' lowercase'>s</span> clothes suitable for this season of the year in our most up-to-date and largest collection</p>
            <button className='text-shopiBlack bg-white font-semibold p-4 py-2 flex items-center lg:text-lg gap-3 align-middle	'>Discover More<BsArrowRightShort className='text-xl lg:text-3xl'/></button>
          </div>
          <div className="images mt-10 flex gap-5 lg:w-3/5">
            <div className="forWomen bg-white/20 w-1/2 h-60 relative lg:h-96"><button className='absolute bottom-2 left-2 flex items-center gap-2 p-3 py-2 bg-shopiBlack text-white'>For Women <BsArrowRightShort className='text-2xl'/></button></div>
            <div className="forMen bg-white/20 w-1/2 h-60 relative lg:-mt-10 lg:h-96"><button className='absolute bottom-2 left-2 flex items-center gap-2 p-3 py-2 bg-shopiBlack text-white'>For Men <BsArrowRightShort className='text-2xl'/></button></div>
          </div>
        </section>
        <section className="OS bg-white mb-5">
          <header className='p-5 pb-0 flex justify-between my-5'>
            <h1 className='font-bold'>On Sale Products</h1>
            <p className='flex items-center'>View More<BsArrowRightShort className='text-xl'/></p>
          </header>
          <div className="slider my-10 mb-0 flex  overflow-x-scroll">
            <div className="scCard px-2 w-fit">
              <div className="image bg-shopiBlack/40 w-60 h-60 relative">
                <div className="off bg-shopiBlack text-white p-3 absolute right-0 font-semibold">%15</div>
              </div>
              <div className="text py-3">
                <p className='font-bold'>Violet Frill Collar Shirt</p> 
                <div className="price w-2/3 flex justify-between">
                  <p>$80.00</p>
                  <p className='line-through opacity-70'>$180.00</p>
                </div>
              </div>
            </div>
            <div className="scCard px-2 w-fit">
              <div className="image bg-shopiBlack/40 w-60 h-60 relative">
                <div className="off bg-shopiBlack text-white p-3 absolute right-0 font-semibold">%15</div>
              </div>
              <div className="text py-3">
                <p className='font-bold'>Violet Frill Collar Shirt</p> 
                <div className="price w-2/3 flex justify-between">
                  <p>$80.00</p>
                  <p className='line-through opacity-70'>$180.00</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="POW bg-white mb-5">
          <header className='p-5 pb-0 flex justify-between my-5'>
            <h1 className='font-bold'>Product Of The Week</h1>
            <p className='flex items-center'>View More<BsArrowRightShort className='text-xl'/></p>
          </header>
          <div className="pofCont mx-5 bg-shopiBlack text-white flex">
            <div className="image w-[40%] h-fill bg-white/40"></div>
            <div className="text w-[60%] flex flex-col gap-2 p-5">
              <h1 className='font-semibold'>Cotton Black T-Shirt</h1>
              <p className=' text-sm mb-4'>Super light and comfortable cotton t-shirt without causing sensitivity to thee body</p>
              <div className="price my-2 flex justify-between items-center">
                <p className='font-semibold'>$125.98</p>
                <div className="stars flex">
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                  <AiFillStar/>
                </div>
              </div>
              <button className='bg-white text-shopiBlack flex items-center self-end p-4 py-2 text-sm font-semibold gap-2'>Buy Now <BsArrowRightShort className='text-xl'/></button>
            </div>
          </div>
        </section>
        <section className="OHC bg-white mb-5">
          <header className='p-5 pb-0 flex justify-between my-5'>
            <h1 className='font-bold'>Our Happy Customers</h1>
            <p className='flex items-center'>View More<BsArrowRightShort className='text-xl'/></p>
          </header>         
        </section>
      </main>
    </>
  )
}
